# Generated by Django 4.0.3 on 2022-04-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_ful_name_person_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hobby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
